window.EDITORIAL_FR = {
  "nav.about": "À propos",
  "nav.experience": "Expérience",
  "nav.contact": "Contact",
  "nav.projects": "Projets",
  "nav.insights": "Blogs",
  "nav.companies": "Pour les entreprises",
  "hero.intro": "Je m’appelle Daksh. Je travaille sur la durabilité, le reporting et les achats responsables.",
  "hero.location": "Paris, France · Anglais / Français / Hindi",
  "hero.footer": "Stratégie RSE · Bilan carbone · Reporting",
  "hero.scroll": "Découvrir mon expérience",
  "about.lede": "Je travaille avec les équipes pour concrétiser leurs projets de durabilité.",
  "about.body": "Mon parcours couvre la technologie et la logistique, avec un intérêt pour le reporting, les achats et les données.",
  "about.link": "Pour votre entreprise",
  "experience.intro": "Reporting, achats et opérations dans la technologie et la logistique.",
  "job1.body": "Benchmarking ESG, engagement fournisseurs et données GES pour le rapport RSE 2026. Appui aux associations via le programme AI for Good de Dataiku.",
  "beyond.body": "Échecs, sport et voyages.",
  "contact.body": "Un poste, un projet ou un défi de durabilité en tête ? Parlons-en.",
  "footer.blurb": "Stratégie de durabilité, données et mise en œuvre. Basé à Paris.",
  "li.s1": "L’empreinte carbone des habitudes quotidiennes et des pistes concrètes pour la réduire.",
  "li.s2": "Un aperçu du travail RSE chez CEVA Logistics.",
  "li.s3": "Suivre l’empreinte du café, de sa production à la tasse.",
  "company.eyebrow": "POUR LES ENTREPRISES",
  "company.title1": "Moins de promesses.",
  "company.title2": "Plus de progrès.",
  "company.intro": "Intégrez la durabilité au fonctionnement de votre entreprise. Des priorités claires, des données fiables et des actions mesurables.",
  "company.benefits": "Voir les bénéfices",
  "company.resourcesLink": "Voir les ressources",
  "company.filmLabel": "LA DURABILITÉ EN PRATIQUE",
  "company.filmNote": "Un aperçu en 45 secondes",
  "company.fallback": "Découvrez les bénéfices ci-dessous.",
  "company.strip": "Mon expérience : Dataiku · Thales · CEVA Logistics",
  "company.experience": "Découvrir mon parcours",
  "company.case": "LES BÉNÉFICES",
  "company.caseTitle": "Utile à l’entreprise.",
  "company.caseEm": "Ancré dans l’action.",
  "company.caseIntro": "Six raisons d’agir. Commencez par les priorités de votre organisation.",
  "company.b1.title": "Gérer les risques",
  "company.b1.body": "Identifiez les exigences de reporting qui concernent votre entreprise. Organisez les preuves nécessaires.",
  "company.b2.title": "Repérer les coûts évitables",
  "company.b2.body": "Suivez l’énergie, les matières et les déchets pour repérer les pertes de ressources et de budget.",
  "company.b3.title": "Éclairer le financement",
  "company.b3.body": "Donnez aux prêteurs et investisseurs une vision claire de votre performance, de vos risques et de vos plans.",
  "company.b4.title": "Mobiliser vos équipes",
  "company.b4.body": "Transformez les engagements en projets concrets, avec des responsabilités claires et des progrès visibles.",
  "company.b5.title": "Répondre aux attentes clients",
  "company.b5.body": "Répondez aux appels d’offres et questionnaires fournisseurs avec des données ESG cohérentes et traçables.",
  "company.b6.title": "Construire la confiance",
  "company.b6.body": "Appuyez vos engagements sur des preuves. Rendez les progrès faciles à comprendre.",
  "company.library": "LES RESSOURCES",
  "company.libraryTitle": "Un bon point",
  "company.libraryEm": "de départ.",
  "company.libraryIntro": "Allez directement à la source. Normes, guides et outils pour avancer.",
  "company.r1": "Mesurer les émissions des scopes 1, 2 et 3.",
  "company.r2": "Comprendre les objectifs climatiques fondés sur la science.",
  "company.r3": "Préparer les déclarations environnementales.",
  "company.r4": "Structurer le reporting de durabilité.",
  "company.r5": "Explorer les principes de conduite responsable.",
  "company.r6": "Consulter les normes européennes de durabilité.",
  "company.r7": "Explorer les activités et critères techniques.",
  "company.r8": "Évaluer l’impact global de votre entreprise.",
  "company.next": "ÉCHANGEONS",
  "company.contactTitle": "À quoi ressemble",
  "company.contactEm": "votre prochain progrès ?",
  "company.contactBody": "Un enjeu de reporting, un projet achats ou un poste dans votre équipe. Parlons de vos besoins.",
  "company.email": "Échangeons",
  "hero.eyebrow": "RSE · ESG · Durabilité",
  "about.label": "À propos",
  "about.title1": "Apprendre",
  "about.title2": "en faisant.",
  "beyond.title1": "En dehors",
  "beyond.title2": "du travail.",
  "hero.commitments": "Transformer les engagements de durabilité en",
  "hero.impact": "impact mesurable",
  "contact.simple": "Me contacter",
  "journey.label": "EXPÉRIENCE",
  "journey.heading": "Mon parcours.",
  "journey.0.date": "2025 — Aujourd’hui",
  "journey.0.role": "Alternant Durabilité et Impact Social",
  "journey.0.body": "Appui au reporting ESG, à l’engagement fournisseurs et au programme AI for Good.",
  "journey.1.date": "Mars — Août 2025",
  "journey.1.role": "Consultant RSE — Stage",
  "journey.1.body": "Appui aux équipes Achats pour structurer et automatiser les achats responsables.",
  "journey.2.date": "Avr. — Oct. 2024",
  "journey.2.role": "Chargé de relation client RSE — Stage",
  "journey.2.body": "Contribution au CDP, à EcoVadis et au reporting de durabilité des clients.",
  "journey.3.date": "Juil. — Déc. 2022",
  "journey.3.role": "Process Manager — Stage",
  "journey.3.body": "Utilisation d’Excel et SQL pour accompagner les opérations du service client.",
  "work.label": "PROJETS",
  "work.heading": "Quelques projets.",
  "work.more": "Autres projets (7)",
  "social.label": "SUR LINKEDIN",
  "social.heading": "Notes sur la durabilité.",
  "social.title0": "Habitudes du quotidien et impact.",
  "social.title1": "La durabilité chez CEVA Logistics",
  "social.title2": "Du grain à la tasse",
  "hobby.label": "EN DEHORS DU TRAVAIL",
  "hobby.heading": "Un autre rythme.",
  "hobby.photo0": "Le prochain coup.",
  "hobby.photo1": "Un nouveau regard.",
  "hobby.photo2": "La prochaine séance.",
  "hobby.photo3": "Un coup à la fois.",
  "hobby.photo4": "Ailleurs.",
  "hobby.photo5": "Continuer.",
  "hobby.back": "Retour à mes projets",
  "company.resourcesShort": "Ressources utiles.",
  "company.pageName": "Pour les entreprises",
  "company.scroll": "Découvrir",
  "company.storyTitle": "La durabilité",
  "company.storyEm": "au travail.",
  "scene.0.kicker": "Risques et reporting",
  "scene.0.step0": "Données",
  "scene.0.step1": "Preuves",
  "scene.0.step2": "Décisions",
  "scene.0.title": "Décider en connaissance de cause.",
  "scene.0.body": "Comprendre les risques. Fournir aux prêteurs et investisseurs des informations claires et traçables.",
  "scene.1.kicker": "Opérations et équipes",
  "scene.1.step0": "Énergie",
  "scene.1.step1": "Matières",
  "scene.1.step2": "Équipes",
  "scene.1.title": "Mieux utiliser les ressources.",
  "scene.1.body": "Repérer les pertes d’énergie, de matières et de temps. Mobiliser les équipes pour les réduire.",
  "scene.2.kicker": "Clients et crédibilité",
  "scene.2.step0": "Mesurer",
  "scene.2.step1": "Documenter",
  "scene.2.step2": "Partager",
  "scene.2.title": "Appuyer la confiance sur des preuves.",
  "scene.2.body": "Répondre aux demandes clients avec cohérence. Montrer les progrès et ce qui reste à faire.",
  "co2.custom.source": "Source et année",
  "co2.custom.factor": "Facteur (kgCO₂e/€)",
  "co2.hero.title": "Calculateur CO₂ indicatif",
  "co2.hero.lede": "Estimez vos émissions selon les scopes du GHG Protocol. Vos données restent dans ce navigateur.",
  "co2.basis": "Structure des scopes du GHG Protocol",
  "co2.basis.note": "Estimation indicative · Sans certification ni assurance",
  "co2.basis.method": "Méthode et sources",
  "co2.scopes.s1.body": "Émissions directes de sources détenues ou contrôlées : combustibles et fuites de fluides frigorigènes.",
  "co2.scopes.s2.body": "Émissions indirectes liées à l’énergie achetée. Ce calculateur utilise les facteurs géographiques du réseau électrique.",
  "co2.scopes.s3.body": "Autres émissions indirectes réparties en 15 catégories. Cet outil estime uniquement certaines activités.",
  "co2.scopes.note": "Couverture partielle : combustibles et fluides courants, électricité et chaleur achetées, et certaines activités du scope 3. Les procédés industriels, la plupart des catégories de chaîne de valeur et le scope 2 contractuel ne sont pas calculés.",
  "co2.s1.refrig.h": "Pertes mesurées pendant l’exploitation ; exclure le remplissage initial et le gaz récupéré.",
  "co2.s1.oil.h": "Pétrole lampant / kérosène, litres",
  "co2.s2.elec.h": "Utilisez un facteur de réseau géographique publié pour votre région et votre année.",
  "co2.s2.custom": "Saisir le facteur du réseau…",
  "co2.s2.customLabel": "Facteur de réseau publié",
  "co2.s2.customHint": "Émissions de production par kWh. Ne pas utiliser ici un facteur contractuel fournisseur ou de mix résiduel.",
  "co2.s3.spend": "Biens achetés et biens d’équipement",
  "co2.s3.spendNote": "Saisissez un facteur publié avec sa source, son année de prix et sa devise. Aucun facteur par défaut. Le matériel immobilisé relève de la catégorie 2 du scope 3.",
  "co2.s3.wttLabel": "Ajouter l’amont des combustibles",
  "co2.s3.wttHint": "Utilise un facteur DESNZ 2026 propre à chaque combustible. L’amont de l’électricité et les pertes réseau sont exclus.",
  "co2.s3.hotel": "Hôtel · facteur France",
  "co2.s3.hotel.h": "Nuitées par chambre ; moyenne France DESNZ 2026",
  "co2.s3.commPt": "Trajets domicile-travail en train · facteur UK",
  "co2.s3.commPt.h": "Passagers-km ; train national britannique",
  "co2.method.title": "Méthode et sources",
  "co2.method.sub": "Donnée d’activité × facteur d’émission = kgCO₂e. Les facteurs et la couverture sont détaillés ci-dessous.",
  "co2.method.new0.title": "Base comptable",
  "co2.method.new0.body": "Utilise les définitions des scopes du Corporate Standard et certaines méthodes du scope 3. Un inventaire conforme complet exige davantage de périmètres, de catégories et de déclarations.",
  "co2.method.new1.title": "Scope 2",
  "co2.method.new1.body": "Électricité selon la méthode géographique uniquement. Lorsque requis, un résultat contractuel distinct doit respecter les critères du Scope 2 Guidance. Cet outil ne le fournit pas.",
  "co2.method.new2.title": "Facteurs d’émission",
  "co2.method.new2.body": "Les facteurs intégrés sont vérifiés dans DESNZ 2026. La plupart concernent le Royaume-Uni ; les hôtels, la France. Réseau et dépenses exigent une source publiée. Les vols excluent le forçage radiatif hors CO₂.",
  "co2.method.new3.title": "Le rôle de GRI",
  "co2.method.new3.body": "GRI encadre la publication d’informations de durabilité. Ce n’est pas une base de facteurs, et ce calculateur n’est ni un rapport GRI ni un inventaire certifié.",
  "co2.method.libLabel": "Bibliothèque de facteurs · DESNZ 2026",
  "co2.method.libNote": "Vérifiée dans le fichier révisé de juillet 2026 (v1.2). Choisissez des facteurs adaptés à l’année, à la géographie et à l’activité.",
  "co2.disclaimer.t": "Estimation indicative.",
  "co2.disclaimer.b": "Estimation partielle, sans vérification. Les activités vides sont exclues, non confirmées nulles. Vérifiez périmètre, couverture et facteurs avant toute publication.",
  "co2.cta.title": "Une question sur la méthode ?",
  "co2.s1.gas.h": "kWh mesurés sur une base de pouvoir calorifique supérieur",
  "co2.s1.oil": "Fioul de chauffage · kérosène",
  "co2.s3.commutePt": "Trajets domicile-travail en train · facteur UK",
  "co2.s3.commutePt.h": "Passagers-km ; train national britannique",
  "co2.s3.air.h": "Vols intérieurs UK ; sans forçage radiatif hors CO₂",
  "co2.s3.airShort.h": "Économie, vers/depuis le UK ; sans forçage radiatif hors CO₂",
  "co2.s3.airLong.h": "Économie, vers/depuis le UK ; sans forçage radiatif hors CO₂",
  "co2.s3.recycled": "Déchets · recyclage en boucle fermée",
  "co2.s3.recycled.h": "Tonnes de déchets commerciaux ; hors compostage",
  "co2.s3.water.h": "Volume identique fourni et traité ; catégories 1 et 5",
  "co2.s2.heat.h": "Facteur indicatif UK pour chaleur et vapeur de réseau, kWh",
  "co2.res.totalLabel": "pour les activités renseignées",
  "p1.b1": "Une plateforme de seconde main entre étudiants, avec collecte sur campus, remise en état et livraison. Le plan couvre les prix, la logistique et le lancement.",
  "p2.b1": "Une analyse de la chaîne de valeur circulaire de FREITAG, des matériaux récupérés à la réparation et à la revente.",
  "p3.b1": "Une analyse du fonds indiciel économie circulaire de BNP Paribas : portefeuille, performance et critères de durabilité.",
  "p4.b1": "Une étude du transport de marchandises, des opérations portuaires et des chaînes logistiques à plus faibles émissions.",
  "p5.b1": "Des scénarios pour SHEIN en Europe, explorant les effets possibles de la réglementation et des attentes sur sa stratégie.",
  "p6.b1": "Une étude du travail des enfants en Bolivie, des pressions économiques, des politiques publiques et de leur application.",
  "p7.b1": "Une analyse Excel de la qualité du service après-vente chez Back Market, pour identifier des tendances et des pistes d’amélioration.",
  "p8.b1": "Une analyse SWOT d’Intel Data Center Manager, portant sur la gestion de l’énergie et le positionnement commercial.",
  "p9.b1": "Six facteurs de mise en œuvre stratégique, étudiés à travers les cas de Samsung et Amazon.",
  "p10.b1": "Un menu de huit pages pour le Restaurant Bharati : mise en page, typographie et fichiers prêts à imprimer.",
  "p11.b1": "Une carte des desserts en français pour le Restaurant Bharati, adaptant le même style visuel à un format plus compact."
};
