/* Engine for the "Why now" explainer on the for-companies page.

   Timing comes from js/explainer-timing.js, generated by
   tools/build-explainer-timing.py from the explainer's script. A cue in the
   markup is either a number (ms into its scene) or a line id with an offset,
   e.g. data-at="v3c+1500" = 1.5 s after the line "v3c" appears. The build
   checks every cue against the script, so rewording a line re-times the whole
   animation without touching this file.

   Each frame works out the scene and the time inside it, then toggles .on on
   every [data-at] reached and .gone on every [data-out] passed; the CSS does
   the moving. Seeks and scene changes apply with transitions off (.xv-snap)
   so nothing plays backwards. Three more cue kinds:
   - data-fx: a one-shot accent (shake, squash, ring burst). It gets .fx only
     when playback crosses its cue live, never on a seek, while paused or
     under reduced motion, and loses it a second later.
   - data-cam="x y scale [ms] [lin]" on an empty <g data-at>: a camera key.
     The camera is a pure function of the time (keys chain, each easing from
     the pose the previous ones reached), applied as one transform on the
     scene's <svg>; its back layer follows at 0.5x and the grid at 0.2x.
   - data-enter on each scene: "wipe" (a chapter card sweeps across and the
     scene swaps under it), "cut" (an instant cut; the two frames match) or
     "open" (the first scene).

   The captions are the narration and are always on, with *starred* words
   highlighted. Live, the words rise in one by one and the highlight sweeps
   on; after a seek, while paused or under reduced motion they just appear. Sound is short effects only (background music was tried and
   dropped - it read as a drone), synthesised with Web Audio and fired from
   the same cues as the visuals (data-sfx). Autoplay is
   always silent, because browsers only allow sound after a tap; the poster's
   play button, "Tap for sound" and the speaker button turn it on. Nothing
   autoplays under prefers-reduced-motion.

   It handles like a video: a full-screen button (or a double-click on the
   picture), and the usual keys while focus is in the player - space or k to
   play/pause, left/right for the previous/next chapter, m for sound, f for
   full screen. */
(function () {
  'use strict';

  var T = window.XV_TIMING;
  var CUE = /^([a-z]\w*?)([+-]\d+)?$/i;

  function fmt(ms) {
    var s = Math.max(0, Math.floor(ms / 1000));
    return Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0');
  }
  function lang() { return document.documentElement.lang === 'fr' ? 'fr' : 'en'; }

  /* ------------------------------------------------------------------ sound */
  var AC = null, sfxBus = null, noise = null;

  function audio() {
    if (AC) { if (AC.state === 'suspended') AC.resume(); return AC; }
    var Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return null;
    try { if (navigator.audioSession) navigator.audioSession.type = 'playback'; } catch (e) {}
    AC = new Ctx();
    var comp = AC.createDynamicsCompressor();
    comp.threshold.value = -16; comp.ratio.value = 3; comp.attack.value = 0.004; comp.release.value = 0.2;
    comp.connect(AC.destination);
    sfxBus = AC.createGain(); sfxBus.gain.value = 0.55; sfxBus.connect(comp);
    noise = AC.createBuffer(1, AC.sampleRate, AC.sampleRate);
    var d = noise.getChannelData(0);
    for (var i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
    return AC;
  }

  function out(node, pan) {
    if (pan && AC.createStereoPanner) {
      var p = AC.createStereoPanner(); p.pan.value = pan; node.connect(p); p.connect(sfxBus);
    } else node.connect(sfxBus);
  }

  function tone(type, f0, f1, t0, dur, peak, pan) {
    var o = AC.createOscillator(), g = AC.createGain();
    o.type = type;
    o.frequency.setValueAtTime(f0, t0);
    if (f1) o.frequency.exponentialRampToValueAtTime(f1, t0 + dur);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(peak, t0 + 0.006);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);
    o.connect(g); out(g, pan);
    o.start(t0); o.stop(t0 + dur + 0.05);
  }

  function hiss(t0, dur, peak, type, f0, f1, q, pan0, pan1) {
    var s = AC.createBufferSource(), f = AC.createBiquadFilter(), g = AC.createGain();
    s.buffer = noise; s.loop = true;
    f.type = type; f.Q.value = q;
    f.frequency.setValueAtTime(f0, t0);
    if (f1) f.frequency.exponentialRampToValueAtTime(f1, t0 + dur);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(peak, t0 + dur * 0.4);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);
    s.connect(f); f.connect(g);
    if (pan0 !== undefined && AC.createStereoPanner) {
      var p = AC.createStereoPanner();
      p.pan.setValueAtTime(pan0, t0); p.pan.linearRampToValueAtTime(pan1, t0 + dur);
      g.connect(p); p.connect(sfxBus);
    } else g.connect(sfxBus);
    s.start(t0); s.stop(t0 + dur + 0.05);
  }

  function note(freq) {
    return function (t) { tone('sine', freq, 0, t, 0.7, 0.16); tone('sine', freq * 2, 0, t, 0.25, 0.03); };
  }

  /* short, soft and mostly sine-based, so they stay in the background */
  var SFX = {
    pop: function (t) { tone('sine', 740, 430, t, 0.12, 0.2, (Math.random() - 0.5) * 0.4); tone('triangle', 1480, 900, t, 0.05, 0.03); },
    click: function (t) { hiss(t, 0.035, 0.3, 'bandpass', 3400, 2600, 2); tone('sine', 1900, 1300, t, 0.03, 0.06); },
    whoosh: function (t) { hiss(t, 0.55, 0.11, 'bandpass', 360, 2600, 0.8, -0.7, 0.7); },
    stamp: function (t) { tone('sine', 160, 46, t, 0.28, 0.5); hiss(t, 0.09, 0.22, 'lowpass', 1500, 380, 0.7); },
    chime: function (t) { tone('sine', 1046.5, 0, t, 1.1, 0.1); tone('sine', 1568, 0, t + 0.08, 1.2, 0.08); tone('sine', 2093, 0, t + 0.08, 0.5, 0.02); },
    swoosh: function (t) { tone('sine', 330, 900, t, 0.16, 0.08); hiss(t, 0.2, 0.05, 'highpass', 1800, 4600, 0.7, 0.5, -0.5); },
    rise: function (t) { tone('triangle', 220, 440, t, 0.5, 0.07); hiss(t, 0.5, 0.04, 'bandpass', 600, 3200, 1.2); },
    blips: function (t) { for (var i = 0; i < 3; i++) tone('sine', 1320 + i * 190, 0, t + i * 0.17, 0.06, 0.06, -0.5 + i * 0.5); },
    wipe: function (t) { hiss(t, 0.42, 0.1, 'bandpass', 380, 3000, 0.9, -0.8, 0.8); tone('sine', 150, 90, t + 0.3, 0.22, 0.1); },
    tick: function (t) { tone('sine', 2200, 1750, t, 0.035, 0.05, (Math.random() - 0.5) * 0.6); },
    lock: function (t) { tone('triangle', 880, 0, t, 0.07, 0.06); tone('sine', 1318.5, 0, t + 0.045, 0.16, 0.06); },
    thud: function (t) { tone('sine', 120, 42, t, 0.32, 0.45); hiss(t, 0.05, 0.16, 'lowpass', 1200, 300, 0.7); },
    snap: function (t) { hiss(t, 0.025, 0.28, 'highpass', 4200, 2600, 1.2); tone('sine', 2400, 1600, t, 0.03, 0.05); },
    note1: note(523.25),
    note2: note(659.25),
    note3: note(783.99),
    note4: note(1046.5)
  };

  function play(name, delay) {
    if (!AC || !SFX[name]) return;
    SFX[name](AC.currentTime + 0.01 + (delay || 0));
  }

  /* ticks under a count-up: dense at first, sparse as the number settles */
  function ticks(duration) {
    if (!AC) return;
    var n = 16, t0 = AC.currentTime + 0.02;
    for (var i = 0; i < n; i++) {
      var p = 1 - Math.pow(1 - i / n, 1 / 3);
      tone('sine', 2300 + i * 25, 0, t0 + p * duration / 1000, 0.025, 0.035);
    }
  }

  /* ----------------------------------------------------------------- player */
  function setup(player) {
    if (!T) { player.classList.add('is-broken'); return; }
    var stage = player.querySelector('.xv-stage');
    var poster = player.querySelector('.xv-poster');
    var playBtn = player.querySelector('.xv-play');
    var soundBtn = player.querySelector('.xv-sound');
    var fullBtn = player.querySelector('.xv-full');
    var unmute = player.querySelector('.xv-unmute');
    var capEl = player.querySelector('.xv-cap');
    var segsBox = player.querySelector('.xv-segs');
    var timeEl = player.querySelector('.xv-time');
    var list = player.parentNode.querySelector('.xv-transcript-list');
    var reduce = matchMedia('(prefers-reduced-motion: reduce)');
    var total = T.total;

    function map(nodes, fn) { return Array.prototype.map.call(nodes, fn); }
    var scenes = map(stage.querySelectorAll('.xv-scene'), function (el, i) {
      var info = T.scenes[i] || { start: 0, dur: 1000 };
      var scene = { el: el, start: info.start, dur: info.dur,
                    enter: el.getAttribute('data-enter') || (i ? 'wipe' : 'open'), camKey: null };
      scene.art = el.querySelector('.xv-art:not(.xv-art--back)');
      scene.back = el.querySelector('.xv-art--back');
      function resolve(value) {
        if (/^-?\d+$/.test(value)) return Number(value);
        var m = CUE.exec(value);
        if (!m || !(m[1] in T.cues)) { if (window.console) console.warn('explainer: unknown cue ' + value); return 0; }
        return T.cues[m[1]] + Number(m[2] || 0) - scene.start;
      }
      scene.items = map(el.querySelectorAll('[data-at]:not([data-cam]),[data-out]'), function (node) {
        return {
          el: node,
          at: node.hasAttribute('data-at') ? resolve(node.getAttribute('data-at')) : Infinity, // exit-only: never .on
          out: node.hasAttribute('data-out') ? resolve(node.getAttribute('data-out')) : Infinity,
          sfx: node.getAttribute('data-sfx'),
          on: null, gone: null
        };
      });
      scene.fx = map(el.querySelectorAll('[data-fx]'), function (node) {
        return { el: node, at: resolve(node.getAttribute('data-fx')), prev: false };
      });
      scene.cam = map(el.querySelectorAll('[data-cam]'), function (node) {
        var raw = node.getAttribute('data-cam').trim(), v = raw.split(/\s+/);
        return { at: resolve(node.getAttribute('data-at') || '0'), x: +v[0] || 0, y: +v[1] || 0, s: +v[2] || 1,
                 dur: /^\d+$/.test(v[3] || '') ? +v[3] : 0, lin: /\blin$/.test(raw) };
      }).sort(function (a, b) { return a.at - b.at; });
      scene.counts = map(el.querySelectorAll('[data-count]'), function (node) {
        var host = node.closest('[data-at]');
        return { el: node, host: host, target: Number(node.getAttribute('data-count')),
                 at: host ? resolve(host.getAttribute('data-at')) : 0,
                 dur: Number(node.getAttribute('data-count-dur') || 1500), shown: null, ticked: false };
      });

      var chapter = el.querySelector('.xv-chapter [id]');
      var btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'xv-seg-btn';
      btn.style.setProperty('--w', info.dur);
      if (chapter) btn.setAttribute('aria-labelledby', chapter.id);
      btn.appendChild(document.createElement('i'));
      btn.addEventListener('click', function (event) { event.stopPropagation(); seek(scene.start); });
      segsBox.appendChild(btn);
      scene.fill = btn.firstChild;
      return scene;
    });

    var t = 0, current = -1, frame = null, last = 0;
    var started = false, ended = false, userPaused = false, pausedByView = false;
    var soundOn = false, capShown = null;

    var totalText = fmt(Math.round(total / 1000) * 1000); // 64.997 s reads 1:05, not 1:04
    poster.querySelector('.xv-poster-time').textContent = totalText;

    function labels() {
      var fr = lang() === 'fr';
      playBtn.setAttribute('aria-label', ended ? (fr ? 'Revoir' : 'Replay') : frame ? 'Pause' : (fr ? 'Lecture' : 'Play'));
      soundBtn.setAttribute('aria-label', fr ? 'Son' : 'Sound');
      soundBtn.setAttribute('aria-pressed', String(soundOn));
      if (fullBtn) fullBtn.setAttribute('aria-label', isFull() ? (fr ? 'Quitter le plein écran' : 'Exit full screen') : (fr ? 'Plein écran' : 'Full screen'));
    }

    /* a caption is a row of word spans (each rises in after the one before),
       with the *starred* words inside a <mark> whose highlight sweeps on; the
       mark and the punctuation right after it are glued so "expected." never
       breaks before its full stop, and French " ?" never starts a line */
    function paint(el, text) {
      el.textContent = '';
      var n = 0, host = el, glue = null;
      function word(parent, w) {
        var span = document.createElement('span');
        span.className = 'w';
        span.style.setProperty('--i', n++);
        span.textContent = w;
        parent.appendChild(span);
      }
      text.replace(/ ([?!:;»])/g, '\u00a0$1').split('*').forEach(function (part, i) {
        if (i % 2) {
          glue = document.createElement('span');
          glue.className = 'xv-glue';
          host = document.createElement('mark');
          glue.appendChild(host);
          el.appendChild(glue);
        } else {
          if (glue) {
            var tail = /^[^ ]+/.exec(part);
            if (tail) { word(glue, tail[0]); part = part.slice(tail[0].length); }
          }
          host = el;
          glue = null;
        }
        part.split(/( +)/).forEach(function (bit) {
          if (!bit) return;
          if (bit.charAt(0) === ' ') host.appendChild(document.createTextNode(' '));
          else word(host, bit);
        });
      });
      el.style.setProperty('--st', Math.min(22, 200 / Math.max(1, n - 1)).toFixed(1) + 'ms');
    }

    function captions(snap) {
      var row = null, rows = T.captions[lang()];
      if (started) {
        for (var i = 0; i < rows.length; i++) {
          if (t >= rows[i].start && t < rows[i].end) { row = rows[i]; break; }
        }
      }
      var text = row ? row.text : '';
      if (text === capShown) return;
      capShown = text;
      if (!text) { capEl.classList.add('is-out'); return; }
      paint(capEl, text);
      capEl.classList.remove('is-out', 'is-in');
      capEl.classList.toggle('is-still', !!(snap || !frame || reduce.matches || t - row.start > 450));
      void capEl.offsetWidth;
      capEl.classList.add('is-in');
    }

    function transcript() {
      if (!list) return;
      var groups = [];
      T.captions[lang()].forEach(function (row) { (groups[row.scene] = groups[row.scene] || []).push(row.text.replace(/\*/g, '')); });
      list.textContent = '';
      groups.forEach(function (lines) {
        var li = document.createElement('li');
        li.textContent = lines.join(' ');
        list.appendChild(li);
      });
    }

    /* ---- camera: keys chain, each easing from the pose the earlier ones reached ---- */
    var K = 1, bg = stage.querySelector('.xv-bg');
    function ease3(p) { return p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2; }
    function easeOut3(p) { return 1 - Math.pow(1 - p, 3); }
    function pose(keys, local, step) { // step: reduced motion jumps to each key at its cue
      var x = 0, y = 0, s = 1;
      for (var i = 0; i < keys.length && keys[i].at <= local; i++) {
        var k = keys[i];
        if (step && k.lin) continue; // a slow linear push is pure motion: reduced motion skips it
        var f = step || !k.dur ? 1 : Math.min(1, (local - k.at) / k.dur);
        if (!k.lin) f = ease3(f);
        x += (k.x - x) * f; y += (k.y - y) * f; s += (k.s - s) * f;
      }
      return [x, y, s];
    }
    function camera(scene, local) {
      if (!scene.art) return;
      var p = pose(scene.cam, local, reduce.matches);
      var key = p.map(function (v) { return v.toFixed(3); }).join();
      if (key === scene.camKey) return; // no style writes while the camera holds
      scene.camKey = key;
      function tf(f, scaled) {
        return 'translate(' + (p[0] * K * f).toFixed(2) + 'px,' + (p[1] * K * f).toFixed(2) + 'px)' +
               (scaled ? ' scale(' + (1 + (p[2] - 1) * f).toFixed(4) + ')' : '');
      }
      scene.art.style.transform = tf(1, true);
      if (scene.back) scene.back.style.transform = tf(0.5, true);
      if (bg) bg.style.transform = tf(0.2, false);
    }
    function measure() { // px per canvas unit, from the untransformed art box (the svg letterboxes 800x480)
      var art = scenes[0] && scenes[0].art;
      if (!art) return;
      var keep = art.style.transform;
      art.style.transform = 'none';
      var r = art.getBoundingClientRect();
      art.style.transform = keep;
      if (r.width && r.height) K = Math.min(r.width / 800, r.height / 480);
      scenes.forEach(function (s) { s.camKey = null; });
    }

    /* ---- chapter wipe: covers from B-320, holds the chapter card to B+140, reveals by B+520 ---- */
    var wipe = stage.querySelector('.xv-wipe');
    var wipeIn = wipe && wipe.querySelector('.xv-wipe-inner');
    var wipeIdx = -1, wipeHeard = -1, W_IN = 320, W_HOLD = 140, W_OUT = 380;
    function wipes(live) {
      if (!wipe) return;
      var idx = -1, x = 0;
      for (var i = 1; i < scenes.length && !reduce.matches; i++) {
        var d = t - scenes[i].start;
        if (scenes[i].enter !== 'wipe' || d < -W_IN || d >= W_HOLD + W_OUT) continue;
        idx = i;
        x = d < 0 ? -100 * (1 - easeOut3((d + W_IN) / W_IN)) : d < W_HOLD ? 0 : 100 * ease3((d - W_HOLD) / W_OUT);
        break;
      }
      if (idx !== wipeIdx) {
        wipeIdx = idx;
        wipe.hidden = idx < 0;
        if (idx > -1) {
          var c = scenes[idx].el.querySelectorAll('.xv-chapter span');
          wipe.querySelector('.xv-wipe-num').textContent = c[0] ? c[0].textContent : '';
          wipe.querySelector('.xv-wipe-title').textContent = c[1] ? c[1].textContent : '';
        }
      }
      if (idx < 0) { wipeHeard = -1; return; }
      wipe.style.transform = 'translate3d(' + x.toFixed(2) + '%,0,0)';
      if (wipeIn) wipeIn.style.transform = 'translate3d(' + (-x * 0.3).toFixed(2) + '%,-50%,0)';
      if (wipeHeard !== idx) { if (live) play('wipe'); wipeHeard = idx; }
    }

    function apply(snap) {
      var idx = scenes.length - 1;
      for (var i = 0; i < scenes.length; i++) {
        if (t < scenes[i].start + scenes[i].dur) { idx = i; break; }
      }
      var scene = scenes[idx];
      var local = Math.min(t - scene.start, scene.dur);
      var changed = idx !== current;
      var moving = !snap && !changed && !!frame; // playing forward, no seek this frame
      var live = moving && soundOn;

      if (changed) {
        scenes.forEach(function (s, i) {
          s.el.classList.toggle('is-active', i === idx);
          s.el.classList.toggle('is-past', i < idx);
          s.el.inert = i !== idx;
        });
        scene.camKey = null;
        current = idx;
      }
      if (changed || snap) scene.el.classList.add('xv-snap');

      scene.items.forEach(function (item) {
        var on = local >= item.at, gone = local >= item.out;
        if (on !== item.on) {
          item.el.classList.toggle('on', on);
          if (on && live && item.sfx && !gone) play(item.sfx);
          item.on = on;
        }
        if (gone !== item.gone) { item.el.classList.toggle('gone', gone); item.gone = gone; }
      });

      /* one-shot accents: only when playback crosses the cue, gone a second later */
      scene.fx.forEach(function (f) {
        var past = local >= f.at;
        if (moving && past && !f.prev && local - f.at < 250 && !reduce.matches) f.el.classList.add('fx');
        if (f.el.classList.contains('fx') && (snap || !past || local - f.at >= 1000)) f.el.classList.remove('fx');
        f.prev = past;
      });

      scene.counts.forEach(function (c) {
        var p = reduce.matches ? (local >= c.at ? 1 : 0) : Math.max(0, Math.min(1, (local - c.at) / c.dur));
        if (p > 0 && !c.ticked && live) { ticks(c.dur); c.ticked = true; }
        if (p === 0) c.ticked = false;
        var text = Math.round(c.target * (1 - Math.pow(1 - p, 3))).toLocaleString(lang() === 'fr' ? 'fr-FR' : 'en-GB');
        if (text !== c.shown) { c.el.textContent = text; c.shown = text; }
      });

      if (changed || snap) {
        void scene.el.getBoundingClientRect();
        scene.el.classList.remove('xv-snap');
      }

      camera(scene, local);
      wipes(live);

      scenes.forEach(function (s, i) {
        s.fill.style.transform = 'scaleX(' + (i < idx ? 1 : i > idx ? 0 : local / s.dur) + ')';
      });
      timeEl.textContent = fmt(t) + ' / ' + totalText;
      captions(snap);
    }

    function tick(now) {
      frame = requestAnimationFrame(tick);
      var dt = last ? Math.min(now - last, 100) : 0;
      last = now;
      t += dt;
      if (t >= total) {
        t = total;
        apply(false);
        stop();
        ended = true;
        player.classList.add('is-ended');
        labels();
        return;
      }
      apply(false);
    }

    function start() {
      if (frame) return;
      if (ended) { ended = false; player.classList.remove('is-ended'); t = 0; current = -1; apply(true); }
      if (!started) { started = true; player.classList.add('is-started'); }
      last = 0;
      frame = requestAnimationFrame(tick);
      player.classList.add('is-playing');
      labels();
    }

    function stop() {
      if (frame) { cancelAnimationFrame(frame); frame = null; }
      player.classList.remove('is-playing');
      labels();
    }

    function seek(ms) {
      t = Math.max(0, Math.min(ms, total - 1));
      if (ended) { ended = false; player.classList.remove('is-ended'); }
      if (!started) { started = true; player.classList.add('is-started'); }
      current = -1;
      apply(true);
      labels();
    }

    function setSound(on) {
      soundOn = on;
      player.classList.toggle('is-sound', on);
      if (on) audio();
      labels();
    }

    function toggle() {
      if (frame) { userPaused = true; stop(); }
      else { userPaused = false; start(); }
    }

    /* previous / next chapter; "previous" first rewinds the current one, like a
       music player, unless it has only just started */
    function jump(dir) {
      var i = Math.max(current, 0);
      if (dir < 0 && t - scenes[i].start > 1500) seek(scenes[i].start);
      else seek(scenes[Math.max(0, Math.min(scenes.length - 1, i + dir))].start);
    }

    /* full screen: the standard API, or Safari's prefixed one; the button stays
       hidden where neither exists (iPhone Safari only lets <video> go full screen) */
    var canFull = !!(fullBtn && (player.requestFullscreen || player.webkitRequestFullscreen) &&
                     (document.fullscreenEnabled || document.webkitFullscreenEnabled));
    function isFull() { return (document.fullscreenElement || document.webkitFullscreenElement) === player; }
    function toggleFull() {
      if (!canFull) return;
      if (isFull()) (document.exitFullscreen || document.webkitExitFullscreen).call(document);
      else {
        var request = (player.requestFullscreen || player.webkitRequestFullscreen).call(player);
        if (request && request.catch) request.catch(function () {});
      }
    }
    function onFullChange() {
      player.classList.toggle('is-full', isFull());
      labels();
    }

    poster.addEventListener('click', function (event) {
      event.stopPropagation();
      userPaused = false;
      setSound(true);
      start();
    });
    playBtn.addEventListener('click', toggle);
    soundBtn.addEventListener('click', function () { setSound(!soundOn); });
    if (canFull) {
      fullBtn.hidden = false;
      fullBtn.addEventListener('click', toggleFull);
      stage.addEventListener('dblclick', function (event) {
        if (!event.target.closest('a,button')) toggleFull();
      });
      document.addEventListener('fullscreenchange', onFullChange);
      document.addEventListener('webkitfullscreenchange', onFullChange);
    }
    player.addEventListener('keydown', function (event) {
      if (event.altKey || event.ctrlKey || event.metaKey) return;
      var key = event.key || '';
      if (key.length === 1) key = key.toLowerCase();
      var onControl = event.target.closest('a,button');
      if (onControl && (key === ' ' || key === 'Enter')) return; // the control's own action
      if (key === ' ' || key === 'k') toggle();
      else if (key === 'ArrowLeft' || key === 'ArrowRight') jump(key === 'ArrowLeft' ? -1 : 1);
      else if (key === 'm') setSound(!soundOn);
      else if (key === 'f' && canFull) toggleFull();
      else return;
      event.preventDefault();
    });
    unmute.addEventListener('click', function (event) { event.stopPropagation(); setSound(true); if (!frame) start(); });
    stage.addEventListener('click', function (event) {
      if (event.target.closest('a,button')) return;
      toggle();
    });

    if ('ResizeObserver' in window) {
      new ResizeObserver(function () {
        measure();
        if (current > -1) camera(scenes[current], Math.min(t - scenes[current].start, scenes[current].dur));
      }).observe(stage);
    }

    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (entries) {
        var entry = entries[entries.length - 1];
        if (entry.intersectionRatio >= 0.6) {
          if (pausedByView || (!started && !reduce.matches)) {
            pausedByView = false;
            if (!userPaused && !ended) start();
          }
        } else if (!entry.isIntersecting && frame) {
          pausedByView = true;
          stop();
        }
      }, { threshold: [0, 0.6] }).observe(stage);
    }

    document.addEventListener('visibilitychange', function () {
      if (document.hidden && frame) { pausedByView = true; stop(); }
      else if (!document.hidden && pausedByView && !userPaused) { pausedByView = false; start(); }
    });

    /* the language switch rewrites text in place; refresh what this file owns */
    document.querySelectorAll('[data-beta-lang]').forEach(function (b) {
      b.addEventListener('click', function () {
        setTimeout(function () {
          scenes.forEach(function (s) { s.counts.forEach(function (c) { c.shown = null; }); });
          capShown = null;
          wipeIdx = -1;
          apply(false);
          transcript();
          labels();
        }, 0);
      });
    });

    player.xvSeek = seek; // lets a test jump to an exact frame
    player.xvTime = function () { return t; };
    transcript();
    measure();
    apply(true);
    labels();
  }

  function init() { document.querySelectorAll('[data-xv]').forEach(setup); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true });
  else init();
})();
