/* Engine for the "Why now" explainer on the for-companies page.

   Timing comes from js/explainer-timing.js, generated by
   tools/build-explainer-audio.py from the narration script. A cue in the
   markup is either a number (ms into its scene) or a line id with an offset,
   e.g. data-at="v3c+1500" = 1.5 s after the line "v3c" starts. The build
   checks every cue against the script, so rewording a line or changing a
   voice re-syncs the whole animation without touching this file.

   Each frame works out the scene and the time inside it, then toggles .on on
   every [data-at] reached and .gone on every [data-out] passed; the CSS does
   the moving. Seeks and scene changes apply with transitions off (.xv-snap)
   so nothing plays backwards.

   Sound: the voice-over is one file per language (the same timeline), the
   effects and the soft music bed are synthesised with Web Audio and fire
   from the same cues as the visuals (data-sfx). Autoplay is always muted,
   because browsers only allow sound after a tap; the poster's play button
   and the sound button turn it on. Captions show whenever the sound is off,
   unless the viewer switches them off. Nothing autoplays under
   prefers-reduced-motion. */
(function () {
  'use strict';

  var T = window.XV_TIMING;
  var CUE = /^([a-z]\w*?)([+-]\d+)?$/i;

  function fmt(ms) {
    var s = Math.max(0, Math.floor(ms / 1000));
    return Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0');
  }
  function lang() { return document.documentElement.lang === 'fr' ? 'fr' : 'en'; }

  /* ------------------------------------------------------------------ sound */
  var AC = null, sfxBus = null, padBus = null, noise = null, pad = null;

  function audio() {
    if (AC) { if (AC.state === 'suspended') AC.resume(); return AC; }
    var Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return null;
    try { if (navigator.audioSession) navigator.audioSession.type = 'playback'; } catch (e) {}
    AC = new Ctx();
    var comp = AC.createDynamicsCompressor();
    comp.threshold.value = -16; comp.ratio.value = 3; comp.attack.value = 0.004; comp.release.value = 0.2;
    comp.connect(AC.destination);
    sfxBus = AC.createGain(); sfxBus.gain.value = 0.55; sfxBus.connect(comp);
    var soft = AC.createBiquadFilter(); soft.type = 'lowpass'; soft.frequency.value = 1300; soft.Q.value = 0.3;
    padBus = AC.createGain(); padBus.gain.value = 0.0001; padBus.connect(soft); soft.connect(comp);
    noise = AC.createBuffer(1, AC.sampleRate, AC.sampleRate);
    var d = noise.getChannelData(0);
    for (var i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;
    return AC;
  }

  function out(node, pan) {
    if (pan && AC.createStereoPanner) {
      var p = AC.createStereoPanner(); p.pan.value = pan; node.connect(p); p.connect(sfxBus);
    } else node.connect(sfxBus);
  }

  function tone(type, f0, f1, t0, dur, peak, pan) {
    var o = AC.createOscillator(), g = AC.createGain();
    o.type = type;
    o.frequency.setValueAtTime(f0, t0);
    if (f1) o.frequency.exponentialRampToValueAtTime(f1, t0 + dur);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(peak, t0 + 0.006);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);
    o.connect(g); out(g, pan);
    o.start(t0); o.stop(t0 + dur + 0.05);
  }

  function hiss(t0, dur, peak, type, f0, f1, q, pan0, pan1) {
    var s = AC.createBufferSource(), f = AC.createBiquadFilter(), g = AC.createGain();
    s.buffer = noise; s.loop = true;
    f.type = type; f.Q.value = q;
    f.frequency.setValueAtTime(f0, t0);
    if (f1) f.frequency.exponentialRampToValueAtTime(f1, t0 + dur);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(peak, t0 + dur * 0.4);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);
    s.connect(f); f.connect(g);
    if (pan0 !== undefined && AC.createStereoPanner) {
      var p = AC.createStereoPanner();
      p.pan.setValueAtTime(pan0, t0); p.pan.linearRampToValueAtTime(pan1, t0 + dur);
      g.connect(p); p.connect(sfxBus);
    } else g.connect(sfxBus);
    s.start(t0); s.stop(t0 + dur + 0.05);
  }

  function note(freq) {
    return function (t) { tone('sine', freq, 0, t, 0.7, 0.16); tone('sine', freq * 2, 0, t, 0.25, 0.03); };
  }

  /* short, soft and mostly sine-based, so they sit under the voice */
  var SFX = {
    pop: function (t) { tone('sine', 740, 430, t, 0.12, 0.2, (Math.random() - 0.5) * 0.4); tone('triangle', 1480, 900, t, 0.05, 0.03); },
    click: function (t) { hiss(t, 0.035, 0.3, 'bandpass', 3400, 2600, 2); tone('sine', 1900, 1300, t, 0.03, 0.06); },
    whoosh: function (t) { hiss(t, 0.55, 0.11, 'bandpass', 360, 2600, 0.8, -0.7, 0.7); },
    stamp: function (t) { tone('sine', 160, 46, t, 0.28, 0.5); hiss(t, 0.09, 0.22, 'lowpass', 1500, 380, 0.7); },
    chime: function (t) { tone('sine', 1046.5, 0, t, 1.1, 0.1); tone('sine', 1568, 0, t + 0.08, 1.2, 0.08); tone('sine', 2093, 0, t + 0.08, 0.5, 0.02); },
    swoosh: function (t) { tone('sine', 330, 900, t, 0.16, 0.08); hiss(t, 0.2, 0.05, 'highpass', 1800, 4600, 0.7, 0.5, -0.5); },
    rise: function (t) { tone('triangle', 220, 440, t, 0.5, 0.07); hiss(t, 0.5, 0.04, 'bandpass', 600, 3200, 1.2); },
    blips: function (t) { for (var i = 0; i < 3; i++) tone('sine', 1320 + i * 190, 0, t + i * 0.17, 0.06, 0.06, -0.5 + i * 0.5); },
    note1: note(523.25),
    note2: note(659.25),
    note3: note(783.99),
    note4: note(1046.5)
  };

  function play(name, delay) {
    if (!AC || !SFX[name]) return;
    SFX[name](AC.currentTime + 0.01 + (delay || 0));
  }

  /* ticks under a count-up: dense at first, sparse as the number settles */
  function ticks(duration) {
    if (!AC) return;
    var n = 16, t0 = AC.currentTime + 0.02;
    for (var i = 0; i < n; i++) {
      var p = 1 - Math.pow(1 - i / n, 1 / 3);
      tone('sine', 2300 + i * 25, 0, t0 + p * duration / 1000, 0.025, 0.035);
    }
  }

  /* the bed: one soft chord per scene, crossfaded */
  var CHORDS = [[50, 57, 61, 64, 66], [47, 54, 57, 61, 62], [43, 50, 54, 57, 59], [40, 52, 55, 59, 62], [45, 52, 57, 59, 64], [50, 57, 61, 64, 69]];

  function chord(i) {
    if (!AC) return;
    var now = AC.currentTime, old = pad;
    if (old) {
      old.g.gain.cancelScheduledValues(now);
      old.g.gain.setTargetAtTime(0.0001, now, 0.5);
      setTimeout(function () { old.o.forEach(function (o) { try { o.stop(); } catch (e) {} }); }, 3000);
    }
    var g = AC.createGain();
    g.gain.setValueAtTime(0.0001, now);
    g.gain.setTargetAtTime(1, now, 0.9);
    g.connect(padBus);
    pad = { g: g, o: CHORDS[i % CHORDS.length].map(function (midi, k) {
      var osc = AC.createOscillator(), v = AC.createGain();
      osc.type = k ? 'triangle' : 'sine';
      osc.frequency.value = 440 * Math.pow(2, (midi - 69) / 12);
      osc.detune.value = k % 2 ? 6 : -6;
      v.gain.value = k ? 0.2 : 0.45;
      osc.connect(v); v.connect(g); osc.start(now);
      return osc;
    }) };
  }

  function bed(on) {
    if (!AC) return;
    padBus.gain.setTargetAtTime(on ? 0.045 : 0.0001, AC.currentTime, on ? 0.7 : 0.2);
  }

  /* ----------------------------------------------------------------- player */
  function setup(player) {
    if (!T) { player.classList.add('is-broken'); return; }
    var stage = player.querySelector('.xv-stage');
    var poster = player.querySelector('.xv-poster');
    var playBtn = player.querySelector('.xv-play');
    var soundBtn = player.querySelector('.xv-sound');
    var unmute = player.querySelector('.xv-unmute');
    var ccBtn = player.querySelector('.xv-cc');
    var capEl = player.querySelector('.xv-cap');
    var segsBox = player.querySelector('.xv-segs');
    var timeEl = player.querySelector('.xv-time');
    var list = player.parentNode.querySelector('.xv-transcript-list');
    var reduce = matchMedia('(prefers-reduced-motion: reduce)');
    var total = T.total;

    var scenes = Array.prototype.map.call(stage.querySelectorAll('.xv-scene'), function (el, i) {
      var info = T.scenes[i] || { start: 0, dur: 1000 };
      var scene = { el: el, start: info.start, dur: info.dur };
      function resolve(value) {
        if (/^-?\d+$/.test(value)) return Number(value);
        var m = CUE.exec(value);
        if (!m || !(m[1] in T.cues)) { if (window.console) console.warn('explainer: unknown cue ' + value); return 0; }
        return T.cues[m[1]] + Number(m[2] || 0) - scene.start;
      }
      scene.items = Array.prototype.map.call(el.querySelectorAll('[data-at],[data-out]'), function (node) {
        return {
          el: node,
          at: node.hasAttribute('data-at') ? resolve(node.getAttribute('data-at')) : -1,
          out: node.hasAttribute('data-out') ? resolve(node.getAttribute('data-out')) : Infinity,
          sfx: node.getAttribute('data-sfx'),
          on: null, gone: null
        };
      });
      scene.counts = Array.prototype.map.call(el.querySelectorAll('[data-count]'), function (node) {
        var host = node.closest('[data-at]');
        return { el: node, host: host, target: Number(node.getAttribute('data-count')),
                 at: host ? resolve(host.getAttribute('data-at')) : 0,
                 dur: Number(node.getAttribute('data-count-dur') || 1500), shown: null, ticked: false };
      });

      var chapter = el.querySelector('.xv-chapter [id]');
      var btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'xv-seg-btn';
      btn.style.setProperty('--w', info.dur);
      if (chapter) btn.setAttribute('aria-labelledby', chapter.id);
      btn.appendChild(document.createElement('i'));
      btn.addEventListener('click', function (event) { event.stopPropagation(); seek(scene.start); });
      segsBox.appendChild(btn);
      scene.fill = btn.firstChild;
      return scene;
    });

    var voice = new Audio();
    voice.preload = 'none';

    var t = 0, current = -1, frame = null, last = 0;
    var started = false, ended = false, userPaused = false, pausedByView = false;
    var soundOn = false, ccMode = 'auto', capShown = null, waitingSince = 0, lastFix = 0;

    poster.querySelector('.xv-poster-time').textContent = fmt(total);

    function labels() {
      var fr = lang() === 'fr';
      playBtn.setAttribute('aria-label', ended ? (fr ? 'Revoir' : 'Replay') : frame ? 'Pause' : (fr ? 'Lecture' : 'Play'));
      soundBtn.setAttribute('aria-label', fr ? 'Son' : 'Sound');
      soundBtn.setAttribute('aria-pressed', String(soundOn));
      ccBtn.setAttribute('aria-label', fr ? 'Sous-titres' : 'Captions');
    }

    function captions() {
      var show = ccMode === 'on' || (ccMode === 'auto' && !soundOn);
      player.classList.toggle('is-cc', show);
      ccBtn.setAttribute('aria-pressed', String(show));
      var text = '', rows = T.captions[lang()];
      if (show && started) {
        for (var i = 0; i < rows.length; i++) {
          if (t >= rows[i].start && t < rows[i].end) { text = rows[i].text; break; }
        }
      }
      if (text !== capShown) {
        if (text) capEl.textContent = text;
        capEl.classList.toggle('is-on', !!text);
        capShown = text;
      }
    }

    function transcript() {
      if (!list) return;
      var groups = [];
      T.captions[lang()].forEach(function (row) { (groups[row.scene] = groups[row.scene] || []).push(row.text); });
      list.textContent = '';
      groups.forEach(function (lines) {
        var li = document.createElement('li');
        li.textContent = lines.join(' ');
        list.appendChild(li);
      });
    }

    function apply(snap) {
      var idx = scenes.length - 1;
      for (var i = 0; i < scenes.length; i++) {
        if (t < scenes[i].start + scenes[i].dur) { idx = i; break; }
      }
      var scene = scenes[idx];
      var local = Math.min(t - scene.start, scene.dur);
      var changed = idx !== current;
      var live = !snap && !changed && soundOn && frame;

      if (changed) {
        scenes.forEach(function (s, i) {
          s.el.classList.toggle('is-active', i === idx);
          s.el.classList.toggle('is-past', i < idx);
          s.el.inert = i !== idx;
        });
        if (!snap && soundOn && frame && current !== -1) play('whoosh');
        if (soundOn) chord(idx);
        current = idx;
      }
      if (changed || snap) scene.el.classList.add('xv-snap');

      scene.items.forEach(function (item) {
        var on = local >= item.at, gone = local >= item.out;
        if (on !== item.on) {
          item.el.classList.toggle('on', on);
          if (on && live && item.sfx && !gone) play(item.sfx);
          item.on = on;
        }
        if (gone !== item.gone) { item.el.classList.toggle('gone', gone); item.gone = gone; }
      });

      scene.counts.forEach(function (c) {
        var p = Math.max(0, Math.min(1, (local - c.at) / c.dur));
        if (p > 0 && !c.ticked && live) { ticks(c.dur); c.ticked = true; }
        if (p === 0) c.ticked = false;
        var text = Math.round(c.target * (1 - Math.pow(1 - p, 3))).toLocaleString(lang() === 'fr' ? 'fr-FR' : 'en-GB');
        if (text !== c.shown) { c.el.textContent = text; c.shown = text; }
      });

      if (changed || snap) {
        void scene.el.getBoundingClientRect();
        scene.el.classList.remove('xv-snap');
      }

      scenes.forEach(function (s, i) {
        s.fill.style.transform = 'scaleX(' + (i < idx ? 1 : i > idx ? 0 : local / s.dur) + ')';
      });
      timeEl.textContent = fmt(t) + ' / ' + fmt(total);
      captions();
    }

    /* the voice track leads whenever it is audible: visuals follow it */
    function syncVoice(force) {
      if (!soundOn || !frame) { if (!voice.paused) voice.pause(); return; }
      var src = T.audio[lang()];
      if (voice.getAttribute('data-src') !== src) {
        voice.setAttribute('data-src', src);
        voice.src = src;
        force = true;
      }
      if (force || Math.abs(voice.currentTime * 1000 - t) > 250) {
        try { voice.currentTime = t / 1000; } catch (e) {}
      }
      if (voice.paused) {
        var p = voice.play();
        if (p && p.catch) p.catch(function () {});
      }
    }
    voice.addEventListener('loadedmetadata', function () {
      if (soundOn && frame) { try { voice.currentTime = t / 1000; } catch (e) {} }
    });

    function tick(now) {
      frame = requestAnimationFrame(tick);
      var dt = last ? Math.min(now - last, 100) : 0;
      last = now;
      if (soundOn && voice.getAttribute('data-src')) {
        if (!voice.paused && voice.readyState >= 3 && !voice.seeking) {
          waitingSince = 0;
          var vt = voice.currentTime * 1000, next = t + dt, gap = Math.abs(next - vt);
          if (gap < 120) t = next;
          else if (gap < 1500) t = vt; // small drift: the picture follows the voice
          else {
            // the voice lost its place (a seek the server could not serve):
            // keep the picture where it is and put the voice back, never the reverse
            t = next;
            if (now - lastFix > 2000) { lastFix = now; try { voice.currentTime = t / 1000; } catch (e) {} }
          }
        } else if (!waitingSince) {
          waitingSince = now;
        } else if (now - waitingSince > 4000) {
          t += dt; // the file is not coming: carry on silently rather than freeze
        }
      } else {
        t += dt;
      }
      if (t >= total) {
        t = total;
        apply(false);
        stop();
        ended = true;
        player.classList.add('is-ended');
        labels();
        return;
      }
      apply(false);
    }

    function start() {
      if (frame) return;
      if (ended) { ended = false; player.classList.remove('is-ended'); t = 0; current = -1; apply(true); }
      if (!started) { started = true; player.classList.add('is-started'); }
      last = 0;
      waitingSince = 0;
      frame = requestAnimationFrame(tick);
      player.classList.add('is-playing');
      syncVoice(true);
      bed(soundOn);
      labels();
    }

    function stop() {
      if (frame) { cancelAnimationFrame(frame); frame = null; }
      player.classList.remove('is-playing');
      if (!voice.paused) voice.pause();
      bed(false);
      labels();
    }

    function seek(ms) {
      t = Math.max(0, Math.min(ms, total - 1));
      if (ended) { ended = false; player.classList.remove('is-ended'); }
      if (!started) { started = true; player.classList.add('is-started'); }
      current = -1;
      apply(true);
      syncVoice(true);
      labels();
    }

    function setSound(on) {
      soundOn = on;
      player.classList.toggle('is-sound', on);
      if (on) { audio(); chord(current < 0 ? 0 : current); }
      syncVoice(true);
      bed(on && !!frame);
      captions();
      labels();
    }

    function toggle() {
      if (frame) { userPaused = true; stop(); }
      else { userPaused = false; start(); }
    }

    poster.addEventListener('click', function (event) {
      event.stopPropagation();
      userPaused = false;
      setSound(true);
      start();
    });
    playBtn.addEventListener('click', toggle);
    soundBtn.addEventListener('click', function () { setSound(!soundOn); });
    unmute.addEventListener('click', function (event) { event.stopPropagation(); setSound(true); if (!frame) start(); });
    ccBtn.addEventListener('click', function () {
      ccMode = player.classList.contains('is-cc') ? 'off' : 'on';
      captions();
    });
    stage.addEventListener('click', function (event) {
      if (event.target.closest('a,button')) return;
      toggle();
    });

    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (entries) {
        var entry = entries[entries.length - 1];
        if (entry.intersectionRatio >= 0.6) {
          if (pausedByView || (!started && !reduce.matches)) {
            pausedByView = false;
            if (!userPaused && !ended) start();
          }
        } else if (!entry.isIntersecting && frame) {
          pausedByView = true;
          stop();
        }
      }, { threshold: [0, 0.6] }).observe(stage);
    }

    document.addEventListener('visibilitychange', function () {
      if (document.hidden && frame) { pausedByView = true; stop(); }
      else if (!document.hidden && pausedByView && !userPaused) { pausedByView = false; start(); }
    });

    /* the language switch rewrites text in place; refresh what this file owns */
    document.querySelectorAll('[data-beta-lang]').forEach(function (b) {
      b.addEventListener('click', function () {
        setTimeout(function () {
          scenes.forEach(function (s) { s.counts.forEach(function (c) { c.shown = null; }); });
          capShown = null;
          apply(false);
          transcript();
          syncVoice(true);
          labels();
        }, 0);
      });
    });

    player.xvSeek = seek; // lets a test jump to an exact frame
    transcript();
    apply(true);
    labels();
  }

  function init() { document.querySelectorAll('[data-xv]').forEach(setup); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true });
  else init();
})();
