window.EDITORIAL_FR = {
  "nav.about": "À propos",
  "nav.projects": "Projets",
  "nav.companies": "Pour les entreprises",
  "hero.intro": "Moi, c’est Daksh, professionnel de la durabilité à Paris. Je transforme les objectifs ESG en données claires et en actions concrètes.",
  "hero.location": "Paris, France · Anglais / Français / Hindi",
  "hero.footer": "Stratégie RSE · Bilan carbone · Reporting",
  "hero.scroll": "Découvrir mon expérience",
  "about.lede": "J’aide les équipes à mesurer leur impact et à passer à l’action.",
  "about.body": "Reporting ESG chez Dataiku. Achats responsables chez Thales. Notations de durabilité chez CEVA Logistics. Mon fil conducteur : des données utiles, des processus clairs et des progrès mesurables.",
  "about.link": "Pour votre entreprise",
  "experience.intro": "Reporting, achats et opérations dans la technologie et la logistique.",
  "job1.body": "Benchmarking ESG, engagement fournisseurs et données GES pour le rapport RSE 2026. Appui aux associations via le programme AI for Good de Dataiku.",
  "beyond.body": "Échecs, sport et voyages nourrissent ma curiosité en dehors du travail.",
  "contact.body": "Un poste, un projet ou un défi de durabilité en tête ? Parlons-en.",
  "footer.blurb": "Stratégie de durabilité, données et mise en œuvre. Basé à Paris.",
  "li.s1": "L’empreinte carbone des habitudes quotidiennes et des pistes concrètes pour la réduire.",
  "li.s2": "Un aperçu du travail RSE chez CEVA Logistics.",
  "li.s3": "Suivre l’empreinte du café, de sa production à la tasse.",
  "company.eyebrow": "POUR LES ENTREPRISES",
  "company.title1": "Moins de promesses.",
  "company.title2": "Plus de progrès.",
  "company.intro": "Intégrez la durabilité au fonctionnement de votre entreprise. Des priorités claires, des données fiables et des actions mesurables.",
  "company.benefits": "Voir les bénéfices",
  "company.resourcesLink": "Voir les ressources",
  "company.filmLabel": "LA DURABILITÉ EN PRATIQUE",
  "company.filmNote": "Un aperçu en 45 secondes",
  "company.fallback": "Les six bénéfices sont aussi présentés ci-dessous.",
  "company.strip": "Mon expérience : Dataiku · Thales · CEVA Logistics",
  "company.experience": "Découvrir mon parcours",
  "company.case": "LES BÉNÉFICES",
  "company.caseTitle": "Utile à l’entreprise.",
  "company.caseEm": "Ancré dans l’action.",
  "company.caseIntro": "Six raisons d’agir. Commencez par les priorités de votre organisation.",
  "company.b1.title": "Gérer les risques",
  "company.b1.body": "Identifiez les exigences de reporting qui concernent votre entreprise. Organisez les preuves nécessaires.",
  "company.b2.title": "Repérer les coûts évitables",
  "company.b2.body": "Suivez l’énergie, les matières et les déchets pour repérer les pertes de ressources et de budget.",
  "company.b3.title": "Éclairer le financement",
  "company.b3.body": "Donnez aux prêteurs et investisseurs une vision claire de votre performance, de vos risques et de vos plans.",
  "company.b4.title": "Mobiliser vos équipes",
  "company.b4.body": "Transformez les engagements en projets concrets, avec des responsabilités claires et des progrès visibles.",
  "company.b5.title": "Répondre aux attentes clients",
  "company.b5.body": "Répondez aux appels d’offres et questionnaires fournisseurs avec des données ESG cohérentes et traçables.",
  "company.b6.title": "Construire la confiance",
  "company.b6.body": "Appuyez vos engagements sur des preuves. Rendez les progrès faciles à comprendre.",
  "company.library": "LES RESSOURCES",
  "company.libraryTitle": "Un bon point",
  "company.libraryEm": "de départ.",
  "company.libraryIntro": "Allez directement à la source. Normes, guides et outils pour avancer.",
  "company.r1": "Mesurer les émissions des scopes 1, 2 et 3.",
  "company.r2": "Comprendre les objectifs climatiques fondés sur la science.",
  "company.r3": "Préparer les déclarations environnementales.",
  "company.r4": "Structurer le reporting de durabilité.",
  "company.r5": "Explorer les principes de conduite responsable.",
  "company.r6": "Consulter les normes européennes de durabilité.",
  "company.r7": "Explorer les activités et critères techniques.",
  "company.r8": "Évaluer l’impact global de votre entreprise.",
  "company.next": "ÉCHANGEONS",
  "company.contactTitle": "À quoi ressemble",
  "company.contactEm": "votre prochain progrès ?",
  "company.contactBody": "Un enjeu de reporting, un projet achats ou un poste dans votre équipe. Parlons de vos besoins.",
  "company.email": "Échangeons"
};
