import {readFile,writeFile} from 'node:fs/promises';
const dir=new URL('.',import.meta.url);
const data=JSON.parse(await readFile(new URL('content.json',dir),'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const text=(en,fr=en,tag='span',cls='')=>`<${tag}${cls?` class="${cls}"`:''} data-fr="${esc(fr)}">${esc(en)}</${tag}>`;
const local=o=>text(o.en,o.fr);
const path=p=>/^(https?:|mailto:|#)/.test(p)?p:'../'+p;
const img=(src,alt='',cls='',eager=false)=>`<img src="${esc(path(src))}" alt="${esc(alt)}" class="${cls}" loading="${eager?'eager':'lazy'}" decoding="async"${eager?' fetchpriority="high"':''}>`;
const specs=[
 {id:'noir',name:'Noir',num:'01',tone:'Cinematic',fr:'Cinématographique',desc:'Dark canvas. Large images. Slow depth.',descfr:'Fond sombre. Images grand format. Profondeur.',color:'#cdb49a'},
 {id:'grid',name:'Grid',num:'02',tone:'Precision',fr:'Précision',desc:'Cobalt blue. Bold type. Kinetic rhythm.',descfr:'Bleu cobalt. Typographie affirmée. Rythme.',color:'#173cf0'},
 {id:'canopy',name:'Canopy',num:'03',tone:'Immersive',fr:'Immersif',desc:'Deep green. Layered photos. Flowing chapters.',descfr:'Vert profond. Photos superposées. Fluidité.',color:'#c4ed87'},
 {id:'signal',name:'Signal',num:'04',tone:'Digital',fr:'Digital',desc:'Modular panels. Sharp contrast. Subtle 3D.',descfr:'Panneaux modulaires. Contraste. Relief subtil.',color:'#a7bbff'},
 {id:'atelier',name:'Atelier',num:'05',tone:'Gallery',fr:'Galerie',desc:'White space. Exhibition layouts. Moving images.',descfr:'Espace blanc. Mise en scène. Images en mouvement.',color:'#e64a28'}
];
const portrait='assets/logos/profile%20picture.avif';
const mountain='assets/notion/hobbies/travel-1.webp';
const caption=(n,en,fr)=>`<div class="section-top"><span class="index">${n} /</span>${text(en,fr,'h2')}</div>`;
const headline=()=>`<h1>${text('Turning sustainability','Transformer les engagements')} ${text('commitments into','de durabilité en')} ${text('measurable impact','impact mesurable','em')}</h1>`;
const cv=()=>`<a class="text-link" href="../assets/CV_Daksh_2026.pdf" download>${text('Download CV','Télécharger le CV')} <span aria-hidden="true">↓</span></a>`;
const actions=()=>`<div class="hero-actions"><a class="button" href="#work">${text('Explore my work','Mes projets')} <span aria-hidden="true">↗</span></a>${cv()}</div>`;
function hero(s){
 const intro=text('Sustainability, reporting and responsible procurement.','Durabilité, reporting et achats responsables.','p','intro');
 const place=`<span class="place">Paris, France</span>`;
 const photo=`<figure class="hero-photo" data-depth>${img(portrait,'Daksh Mehta','',true)}<figcaption>Daksh Mehta ${text('Sustainability','Durabilité')}</figcaption></figure>`;
 if(s.id==='noir')return `<section class="hero hero-noir"><div class="hero-top"><span>DAKSH MEHTA</span>${place}</div><div class="hero-copy">${headline()}${intro}${actions()}</div>${photo}<span class="hero-side" aria-hidden="true">PORTFOLIO / 2026</span><a class="hero-scroll" href="#work">${text('Scroll to explore','Découvrir')} ↓</a></section>`;
 if(s.id==='grid')return `<section class="hero hero-grid"><div class="hero-top"><span>CSR / ESG</span>${place}</div><div class="grid-title">${headline()}<span class="grid-cross" aria-hidden="true">✳</span></div><div class="grid-bottom"><div>${intro}${actions()}</div><div class="grid-images">${photo}<figure>${img('assets/notion/covers/Pitch_deck_SustainSwap.png','SustainSwap pitch deck','',true)}<figcaption>SustainSwap / ${text('Circular economy','Économie circulaire')}</figcaption></figure></div></div></section>`;
 if(s.id==='canopy')return `<section class="hero hero-canopy"><div class="canopy-view" data-depth>${img(mountain,'Daksh beside a river in the mountains','',true)}</div><div class="hero-top"><span>DAKSH MEHTA / CSR · ESG</span>${place}</div><div class="hero-copy">${headline()}${actions()}</div><div class="canopy-note">${img(portrait,'Daksh Mehta','',false)}${intro}</div><a class="hero-scroll" href="#journey">${text('My journey','Mon parcours')} ↓</a></section>`;
 if(s.id==='signal')return `<section class="hero hero-signal"><div class="signal-title"><div class="hero-top"><span>DAKSH MEHTA / PORTFOLIO</span>${place}</div>${headline()}${intro}${actions()}</div><div class="signal-grid"><div class="signal-profile">${photo}<span class="signal-label">CSR / ESG / DATA</span></div><a class="signal-work" href="#work"><span>${text('Selected work','Projets sélectionnés')} ↗</span><div class="signal-deck">${data.projects.slice(0,3).map((p,i)=>img(p.image,p.title,'deck-'+i)).join('')}</div><span>SustainSwap / Green ETF / Trade & climate</span></a><a class="signal-journey" href="#journey"><span>${text('Experience','Expérience')} ↗</span><div>${data.jobs.slice(0,3).map(j=>`<span>${j.name}</span>`).join('')}</div></a><a class="signal-carbon" href="../co2-tracker.html"><span>GHG Protocol</span><strong>CO₂e</strong>${text('Screening calculator ↗','Calculateur indicatif ↗')}</a></div></section>`;
 return `<section class="hero hero-atelier"><div class="atelier-name" aria-hidden="true">DAKSH<span>MEHTA</span></div><div class="atelier-hero-row"><div class="atelier-intro"><span class="eyebrow">PARIS / CSR / ESG</span>${headline()}${actions()}</div>${photo}<div class="atelier-note"><span class="index">PORTFOLIO / 2026</span>${intro}</div></div></section>`;
}
function job(j,i){return `<article class="job" data-enter style="--i:${i}"><span class="job-number">0${i+1}</span><div class="logo-plate">${img(j.logo,j.name)}</div><div class="job-copy"><h3>${local(j.role)}</h3><p>${local(j.body)}</p></div><div class="job-meta">${local(j.date)}<span>${esc(j.city)}</span></div></article>`}
function journey(s){return `<section id="journey" class="section journey">${caption('02','Experience','Expérience')}<div class="journey-intro">${text('Learning by doing.','Apprendre en faisant.','h3')}${text('I work with teams to put sustainability plans into practice.','Je travaille avec les équipes pour concrétiser leurs projets de durabilité.','p')}</div><div class="jobs">${data.jobs.map(job).join('')}</div><details class="education"><summary>${text('Education & tools','Formation et outils')} <span aria-hidden="true">+</span></summary><div class="education-content">${data.education.map(x=>`<div><h3>${x.name}</h3><p>${local(x.degree)}</p><span>${x.date}</span></div>`).join('')}<p class="tools">GHG accounting · EcoVadis · CDP · CSRD · SBTi · Power BI · Excel & SQL · Power Automate</p></div></details></section>`}
function project(p,i){return `<details class="project" id="${p.id}" data-enter><summary><div class="project-image" data-tilt>${p.image?img(p.image,p.title):`<span class="type-cover">${esc(p.title)}</span>`}<span class="project-plus" aria-hidden="true">+</span></div><div class="project-caption"><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${esc(p.title)}</h3><span class="project-type">${local(p.type)}</span></div></summary><div class="project-body"><p>${local(p.body)}</p><div class="downloads">${p.links.map(a=>`<a href="${esc(path(a.href))}"${a.download?' download':' target="_blank" rel="noopener noreferrer"'}>${esc(a.label)}</a>`).join('')}</div></div></details>`}
function work(s){return `<section id="work" class="section work">${caption('01','Selected work','Projets sélectionnés')}<div class="work-grid">${data.projects.slice(0,4).map(project).join('')}</div><details class="more-work"><summary>${text('More projects','Autres projets')} <span>07 <span aria-hidden="true">+</span></span></summary><div class="work-grid">${data.projects.slice(4).map((p,i)=>project(p,i+4)).join('')}</div></details></section>`}
function company(s){return `<section id="companies" class="section companies">${caption('03','For companies','Pour les entreprises')}<div class="company-layout"><figure class="film" data-enter><video muted playsinline loop controls preload="none" aria-label="Six benefits of sustainability for companies"><source src="${path(data.video)}" type="video/mp4"></video><figcaption>${text('Sustainability in practice','La durabilité en pratique')}<button class="video-toggle" type="button" hidden>${text('Play film','Lire le film')}</button></figcaption></figure><div class="company-copy"><h3>${text('Clear priorities.','Des priorités claires.')}<em>${text('Practical steps.','Des actions concrètes.')}</em></h3><div class="benefits">${[['Better decisions','Mieux décider','Connect risks, reporting and finance.','Relier risques, reporting et financement.'],['Better use of resources','Mieux utiliser les ressources','Track energy, materials and progress.','Suivre l’énergie, les matières et les progrès.'],['More confidence','Renforcer la confiance','Give customers and teams clear evidence.','Apporter des preuves aux clients et aux équipes.']].map((x,i)=>`<details><summary><span class="index">0${i+1}</span>${text(x[0],x[1])}<span>+</span></summary><p>${text(x[2],x[3])}</p></details>`).join('')}</div><a class="text-link" href="../co2-tracker.html">${text('CO₂ screening calculator','Calculateur CO₂ indicatif')} ↗</a><span class="method-note">${text('GHG Protocol scope structure · cited factors','Structure des scopes GHG Protocol · facteurs sourcés')}</span></div></div><details class="resources"><summary>${text('Frameworks & resources','Référentiels et ressources')} <span>+</span></summary><div class="resource-grid">${data.resources.map(r=>`<a href="${r.href}" target="_blank" rel="noopener noreferrer">${r.logo?`<span class="logo-plate">${img(r.logo,r.name)}</span>`:''}<span>${esc(r.name)}</span><span aria-hidden="true">↗</span></a>`).join('')}</div></details></section>`}
const hobbyPhotos=[['chess-1.webp','The next move.','Le prochain coup.','Daksh playing chess'],['travel-1.webp','The next perspective.','Un autre regard.','Daksh beside a mountain river'],['fitness-1.webp','The next session.','La prochaine séance.','Daksh training'],['chess-2.webp','One move at a time.','Un coup à la fois.','Chess'],['travel-2.webp','Somewhere new.','Ailleurs.','Travel'],['fitness-2.webp','Showing up.','Être au rendez-vous.','Fitness']];
function hobbies(s){return `<section id="outside" class="section outside">${caption('04','Outside work','Hors du travail')}<div class="photo-wall">${hobbyPhotos.map((p,i)=>`<figure class="hobby-photo" data-enter style="--i:${i}">${img('assets/notion/hobbies/'+p[0],p[3])}<figcaption>${text(p[1],p[2])}<span class="index">0${i+1}</span></figcaption></figure>`).join('')}</div></section>`}
function posts(s){return `<section id="notes" class="section notes">${caption('05','On LinkedIn','Sur LinkedIn')}<div class="notes-grid">${data.posts.map(p=>`<a href="${p.href}" target="_blank" rel="noopener noreferrer" data-enter>${img(p.image,'')}<h3>${local(p.title)} <span aria-hidden="true">↗</span></h3></a>`).join('')}</div></section>`}
function contact(s){return `<footer id="contact" class="section contact"><span class="eyebrow">${text('Contact','Contact')}</span><a class="contact-title" href="${data.email}">${text('Get in touch.','Échangeons.')} <span aria-hidden="true">↗</span></a><div class="contact-row"><a href="${data.email}">Dakshmehta077@gmail.com</a><a href="https://www.linkedin.com/in/mehtadaksh/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>${cv()}<span>© 2026 Daksh Mehta</span></div></footer>`}
function header(s){return `<a class="skip" href="#main">${text('Skip to content','Aller au contenu')}</a><header class="site-header"><a class="brand" href="#main">dm<span>·</span><span class="brand-name">Daksh Mehta</span></a><nav aria-label="Main navigation"><a href="#work">${text('Work','Projets')}</a><a href="#journey">${text('Experience','Expérience')}</a><a href="#companies">${text('Companies','Entreprises')}</a><a href="#outside">${text('Outside work','Hors du travail')}</a><a href="#contact">${text('Contact','Contact')}</a></nav><div class="header-controls"><button class="language-toggle" type="button" aria-label="Switch to French">FR</button><button class="menu-toggle" aria-expanded="false" aria-label="Open menu" type="button">☰</button></div></header>`}
function switcher(s){return `<aside class="concept-dock" aria-label="Design comparison"><a class="back-comparison" href="index.html">▦ ${text('All designs','Les 5 styles')}</a><div class="concept-links">${specs.map(x=>`<a href="${x.id}.html" aria-label="${x.num} ${x.name}"${s.id===x.id?' aria-current="page"':''}>${x.num}</a>`).join('')}</div><button class="motion-toggle" aria-pressed="false" aria-label="Pause animations" type="button">Ⅱ</button></aside>`}
function head(title){return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><meta name="description" content="Daksh Mehta — sustainability, reporting and responsible procurement. Explore the ${esc(title)} design."><title>${esc(title)} — Daksh Mehta</title><link rel="icon" href="../favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700&family=Instrument+Serif:ital@0;1&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="concepts.css?v=1"><script src="concepts.js?v=1" defer></script></head>`}
for(const s of specs){
 const sections={work:work(s),journey:journey(s),companies:company(s),outside:hobbies(s),notes:posts(s)};
 const order={noir:['work','companies','journey','outside','notes'],grid:['journey','work','companies','notes','outside'],canopy:['journey','outside','companies','work','notes'],signal:['work','journey','companies','outside','notes'],atelier:['work','journey','companies','outside','notes']}[s.id];
 await writeFile(new URL(s.id+'.html',dir),`${head(s.name)}<body class="concept ${s.id}" data-concept="${s.id}">${header(s)}<main id="main">${hero(s)}${order.map(k=>sections[k]).join('')}</main>${contact(s)}${switcher(s)}</body></html>`);
}
function mini(s){
 if(s.id==='noir')return `<div class="mini-top">DAKSH MEHTA <span>PARIS</span></div><strong>Turning<br>sustainability<br>into <em>impact.</em></strong>${img(portrait,'','mini-portrait')}<span class="mini-bottom">01 / CINEMATIC</span>`;
 if(s.id==='grid')return `<div class="mini-top">DAKSH MEHTA <span>CSR / ESG</span></div><strong>MEASURABLE<br>IMPACT<span>✳</span></strong><div class="mini-grid-photos">${img(portrait)}${img('assets/notion/covers/Pitch_deck_SustainSwap.png')}</div>`;
 if(s.id==='canopy')return `${img(mountain,'','mini-landscape')}<div class="mini-top">DAKSH MEHTA <span>PARIS</span></div><strong>Commitments.<br><em>Into impact.</em></strong><span class="mini-bottom">SUSTAINABILITY / IN PRACTICE</span>`;
 if(s.id==='signal')return `<div class="mini-top">DM / PORTFOLIO <span>2026</span></div><strong>Turning commitments<br>into <em>impact.</em></strong><div class="mini-panels"><div>${img(portrait)}</div><div>${img('assets/notion/covers/Green_ETF_BNP_Paribas.png')}</div><div><span>GHG PROTOCOL</span><b>CO₂e</b></div></div>`;
 return `<div class="mini-top">PORTFOLIO <span>PARIS / FRANCE</span></div><strong>DAKSH<br>MEHTA</strong>${img(portrait,'','mini-portrait')}<span class="mini-bottom">SUSTAINABILITY. IN PRACTICE.</span>`;
}
await writeFile(new URL('index.html',dir),`${head('Five directions')}<body class="comparison"><header class="comparison-header"><a class="brand" href="../index.html">dm<span>·</span><span class="brand-name">Daksh Mehta</span></a><a href="../index.html">${text('Current website','Site actuel')} ↗</a><button class="language-toggle" aria-label="Switch to French" type="button">FR</button></header><main id="main" class="comparison-main"><div class="comparison-intro"><span class="eyebrow">DESIGN EXPLORATIONS / 01—05</span>${text('One story. Five directions.','Un parcours. Cinq directions.','h1')}${text('Explore each website. Feel the difference.','Explorez chaque site. Découvrez les différences.','p')}</div><div class="comparison-grid">${specs.map(s=>`<a class="design-card" href="${s.id}.html"><div class="design-preview mini-${s.id}">${mini(s)}</div><div class="design-card-title"><span class="index">${s.num}</span><h2>${s.name}</h2><span>${text(s.tone,s.fr)}</span><span aria-hidden="true">↗</span></div>${text(s.desc,s.descfr,'p')}</a>`).join('')}</div><p class="comparison-note">${text('Five complete, interactive directions. Same projects, experience and resources.','Cinq directions complètes et interactives. Les mêmes projets, expériences et ressources.')}</p></main></body></html>`);
console.log('Built comparison page and five complete design directions.');
